Config params are now in yaml
iotaledger-archive/res-sim-tangle pull request #2
Opened 2021-07-18 18:32 UTC by GalRogozinski

# Description

Use hive.go config framework to pass params via yaml. Now no recompilation is needed when changing params.

2021-07-19 08:01 UTC, apenzk requested changes

2021-07-19 08:01 UTC, apenzk commented on parameters.yml
> +  minCut:            51  # cut data close to the genesis (multiply by lambda)
```suggestion
  minCut:            51  # cut data close to the genesis (value in units of lambda)
```

2021-07-19 08:01 UTC, apenzk commented on parameters.yml
> +  maxCutrange:       52  # cut data for the most recent txs, not applied for every analysis (multiplied by lambda)
```suggestion
  maxCutrange:       52  # cut data for the most recent txs, not applied for every analysis (value in units of lambda)
```

2021-07-19 08:01 UTC, apenzk commented on parameters.yml
> +  TangleSize: 300        # Number of message * lambda
```suggestion
  TangleSize: 300        # Number of messages / lambda
```

2021-07-19 08:01 UTC, apenzk commented on parameters.go
> +	p.TangleSize = p.TangleSize * lambdaForSize
this will be confusing when somebody is working on the code. We should do sth like 
p.TangleSize = p.TangleSizeNormalized * lambdaForSize
and define TangleSizeNormalized in the parameter file instead

2021-07-19 08:01 UTC, apenzk commented on parameters.go
> +	p.MinCut = p.MinCut * lambdaForSize
same for MinCut and MaxCut

2021-07-19 08:07 UTC, apenzk requested changes

2021-07-19 08:07 UTC, apenzk commented on parameters.go
> +		p.D = int(age)
"age" must be "variable"
because we want to be able to change what kind of parameter we want to vary, 
variable could be D (age) or K or lambda, etc.. 
the easiest solution would be 
if variable != -1 {
		//p.D = int(variable)		
		p.K = int(variable)
		// p.lambda = variable
		// etc...
and uncomment dependent on what we want to vary

2021-07-19 08:23 UTC, GalRogozinski commented on parameters.yml
> +  TangleSize: 300        # Number of message * lambda
shouldn't be in units of lambda as well?
currently in the code we are multiplying it...

2021-07-19 08:39 UTC, apenzk commented on parameters.yml
> +  TangleSize: 300        # Number of message * lambda
yes the tangle size here is in units of lambda.. which equals to number of messages div lambda

2021-07-21 07:39 UTC, apenzk approved these changes

2021-07-21 07:45 UTC, merged